### ISSUE TITLE
Unit card too big for landscape.

### ISSUE THREAD

**Issue by Inublade** [gregchiasson/warhams#9]
Only having the issue with Hive Tyrant with wings but its cutting off the bottom of the card since it has so many rules.
![image](https://user-images.githubusercontent.com/57345904/68107501-b10faa00-feaa-11e9-964f-0871119a3ec1.png)

**Comment by balintgaspar** [comment]
I just run into that problem I forked that repo and I will update the code, keep you posted

**Comment by MaxHzg** [comment]
As of today, it seems the same problem still occurs.
![grafik](https://user-images.githubusercontent.com/60782594/75625510-1eb0b600-5bbf-11ea-949e-f617451a4b73.png)

**Comment by Inublade** [comment]
Did you check the big sheet box? It worked for me

**Comment by gregchiasson** [comment]
Jesus that's a lot of rules.
